extractStylesSampleServerPort = 32459;
var port = extractStylesSampleServerPort;

extractStylesCases = [
  { // Error test case #1
    options: {
      html: [
        '<html test-ignore><head>',
        '<link rel="stylesheet" media="" ',
          'href="http://notrealurl/aaaaa.css" type="">',
        '</head><body test-ignore>',
        '<h1>Hello <em>world!</em></h1>',
        '</body></html>'
      ].join('\n'),
      url: 'http://localhost:' + port,
      widths: [1024, 720]
    },
    output: {
      "error":500,
      "reason":{
        "code":"resource-failed",
        "data":[
          "http://notrealurl/aaaaa.css"
        ]
      }
    }
  },
  { // Successful test case #1
    options: {
      html: [
        '<html test-ignore><head>',
        '<link rel="stylesheet" media="" ',
          'href="http://localhost:' + port + '/sample.css" type="">',
        '</head><body test-ignore>',
        '<h1>Hello <em>world!</em></h1>',
        '</body></html>'
      ].join('\n'),
      url: 'http://localhost:' + port,
      widths: [1024, 720]
    },
    output: {
      "720":[
        {
          "attributes":{
            "-webkit-animation-delay":"0s",
            "-webkit-animation-direction":"normal",
            "-webkit-animation-duration":"0s",
            "-webkit-animation-fill-mode":"none",
            "-webkit-animation-iteration-count":"1",
            "-webkit-animation-name":"none",
            "-webkit-animation-play-state":"running",
            "-webkit-animation-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-appearance":"none",
            "-webkit-backface-visibility":"visible",
            "-webkit-background-clip":"border-box",
            "-webkit-background-composite":"source-over",
            "-webkit-background-origin":"padding-box",
            "-webkit-background-size":"auto auto",
            "-webkit-border-fit":"border",
            "-webkit-border-horizontal-spacing":"0px",
            "-webkit-border-image":"none",
            "-webkit-border-vertical-spacing":"0px",
            "-webkit-box-align":"stretch",
            "-webkit-box-direction":"normal",
            "-webkit-box-flex":"0",
            "-webkit-box-flex-group":"1",
            "-webkit-box-lines":"single",
            "-webkit-box-ordinal-group":"1",
            "-webkit-box-orient":"horizontal",
            "-webkit-box-pack":"start",
            "-webkit-box-reflect":"none",
            "-webkit-box-shadow":"none",
            "-webkit-color-correction":"default",
            "-webkit-column-break-after":"auto",
            "-webkit-column-break-before":"auto",
            "-webkit-column-break-inside":"auto",
            "-webkit-column-count":"auto",
            "-webkit-column-gap":"normal",
            "-webkit-column-rule-color":"rgb(255, 0, 0)",
            "-webkit-column-rule-style":"none",
            "-webkit-column-rule-width":"0px",
            "-webkit-column-span":"1",
            "-webkit-column-width":"auto",
            "-webkit-font-smoothing":"auto",
            "-webkit-highlight":"none",
            "-webkit-hyphenate-character":"auto",
            "-webkit-hyphenate-limit-after":"auto",
            "-webkit-hyphenate-limit-before":"auto",
            "-webkit-hyphens":"manual",
            "-webkit-line-box-contain":"block inline replaced",
            "-webkit-line-break":"normal",
            "-webkit-line-clamp":"none",
            "-webkit-locale":"auto",
            "-webkit-margin-after-collapse":"collapse",
            "-webkit-margin-before-collapse":"collapse",
            "-webkit-marquee-direction":"auto",
            "-webkit-marquee-increment":"6px",
            "-webkit-marquee-repetition":"infinite",
            "-webkit-marquee-style":"scroll",
            "-webkit-mask-attachment":"scroll",
            "-webkit-mask-box-image":"none",
            "-webkit-mask-clip":"border-box",
            "-webkit-mask-composite":"source-over",
            "-webkit-mask-image":"none",
            "-webkit-mask-origin":"border-box",
            "-webkit-mask-position":"0% 0%",
            "-webkit-mask-repeat":"repeat",
            "-webkit-mask-size":"auto auto",
            "-webkit-nbsp-mode":"normal",
            "-webkit-perspective":"none",
            "-webkit-perspective-origin":"352px 21px",
            "-webkit-rtl-ordering":"logical",
            "-webkit-svg-shadow":"none",
            "-webkit-text-combine":"none",
            "-webkit-text-decorations-in-effect":"none",
            "-webkit-text-emphasis-color":"rgb(255, 0, 0)",
            "-webkit-text-emphasis-position":"over",
            "-webkit-text-emphasis-style":"none",
            "-webkit-text-fill-color":"rgb(255, 0, 0)",
            "-webkit-text-orientation":"vertical-right",
            "-webkit-text-security":"none",
            "-webkit-text-stroke-color":"rgb(255, 0, 0)",
            "-webkit-text-stroke-width":"0px",
            "-webkit-transform":"none",
            "-webkit-transform-origin":"352px 21px",
            "-webkit-transform-style":"flat",
            "-webkit-transition-delay":"0s",
            "-webkit-transition-duration":"0s",
            "-webkit-transition-property":"all",
            "-webkit-transition-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-user-drag":"auto",
            "-webkit-user-modify":"read-only",
            "-webkit-user-select":"text",
            "-webkit-writing-mode":"horizontal-tb",
            "alignment-baseline":"auto",
            "background-attachment":"scroll",
            "background-clip":"border-box",
            "background-color":"rgba(0, 0, 0, 0)",
            "background-image":"none",
            "background-origin":"padding-box",
            "background-position":"0% 0%",
            "background-repeat":"repeat",
            "background-size":"auto auto",
            "baseline-shift":"baseline",
            "border-bottom-color":"rgb(255, 0, 0)",
            "border-bottom-left-radius":"0px",
            "border-bottom-right-radius":"0px",
            "border-bottom-style":"none",
            "border-bottom-width":"0px",
            "border-collapse":"separate",
            "border-left-color":"rgb(255, 0, 0)",
            "border-left-style":"none",
            "border-left-width":"0px",
            "border-right-color":"rgb(255, 0, 0)",
            "border-right-style":"none",
            "border-right-width":"0px",
            "border-top-color":"rgb(255, 0, 0)",
            "border-top-left-radius":"0px",
            "border-top-right-radius":"0px",
            "border-top-style":"none",
            "border-top-width":"0px",
            "bottom":"auto",
            "box-shadow":"none",
            "box-sizing":"content-box",
            "caption-side":"top",
            "clear":"none",
            "clip":"auto",
            "clip-path":"none",
            "clip-rule":"nonzero",
            "color":"rgb(255, 0, 0)",
            "color-interpolation":"srgb",
            "color-interpolation-filters":"linearrgb",
            "color-rendering":"auto",
            "cursor":"auto",
            "direction":"ltr",
            "display":"block",
            "dominant-baseline":"auto",
            "empty-cells":"show",
            "fill":"#000000",
            "fill-opacity":"1",
            "fill-rule":"nonzero",
            "filter":"none",
            "float":"none",
            "flood-color":"rgb(0, 0, 0)",
            "flood-opacity":"1",
            "font-family":"'Nimbus Sans L'",
            "font-size":"32px",
            "font-style":"normal",
            "font-variant":"normal",
            "font-weight":"bold",
            "glyph-orientation-horizontal":"0deg",
            "glyph-orientation-vertical":"auto",
            "height":"42px",
            "image-rendering":"auto",
            "kerning":"0",
            "left":"auto",
            "letter-spacing":"normal",
            "lighting-color":"rgb(255, 255, 255)",
            "line-height":"normal",
            "list-style-image":"none",
            "list-style-position":"outside",
            "list-style-type":"disc",
            "margin-bottom":"21px",
            "margin-left":"0px",
            "margin-right":"0px",
            "margin-top":"21px",
            "marker-end":"none",
            "marker-mid":"none",
            "marker-start":"none",
            "mask":"none",
            "max-height":"none",
            "max-width":"none",
            "min-height":"0px",
            "min-width":"0px",
            "opacity":"1",
            "orphans":"2",
            "outline-color":"rgb(255, 0, 0)",
            "outline-style":"none",
            "outline-width":"0px",
            "overflow-x":"visible",
            "overflow-y":"visible",
            "padding-bottom":"0px",
            "padding-left":"0px",
            "padding-right":"0px",
            "padding-top":"0px",
            "page-break-after":"auto",
            "page-break-before":"auto",
            "page-break-inside":"auto",
            "pointer-events":"auto",
            "position":"static",
            "resize":"none",
            "right":"auto",
            "shape-rendering":"auto",
            "speak":"normal",
            "stop-color":"rgb(0, 0, 0)",
            "stop-opacity":"1",
            "stroke":"none",
            "stroke-dasharray":"none",
            "stroke-dashoffset":"0",
            "stroke-linecap":"butt",
            "stroke-linejoin":"miter",
            "stroke-miterlimit":"4",
            "stroke-opacity":"1",
            "stroke-width":"1",
            "table-layout":"auto",
            "text-align":"-webkit-auto",
            "text-anchor":"start",
            "text-decoration":"none",
            "text-indent":"0px",
            "text-overflow":"clip",
            "text-rendering":"auto",
            "text-shadow":"none",
            "text-transform":"none",
            "top":"auto",
            "unicode-bidi":"normal",
            "vector-effect":"none",
            "vertical-align":"baseline",
            "visibility":"visible",
            "white-space":"normal",
            "widows":"2",
            "width":"704px",
            "word-break":"normal",
            "word-spacing":"0px",
            "word-wrap":"normal",
            "writing-mode":"lr-tb",
            "z-index":"auto",
            "zoom":"1"
          },
          "children":[
            {
              "attributes":{
                "-webkit-animation-delay":"0s",
                "-webkit-animation-direction":"normal",
                "-webkit-animation-duration":"0s",
                "-webkit-animation-fill-mode":"none",
                "-webkit-animation-iteration-count":"1",
                "-webkit-animation-name":"none",
                "-webkit-animation-play-state":"running",
                "-webkit-animation-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
                "-webkit-appearance":"none",
                "-webkit-backface-visibility":"visible",
                "-webkit-background-clip":"border-box",
                "-webkit-background-composite":"source-over",
                "-webkit-background-origin":"padding-box",
                "-webkit-background-size":"auto auto",
                "-webkit-border-fit":"border",
                "-webkit-border-horizontal-spacing":"0px",
                "-webkit-border-image":"none",
                "-webkit-border-vertical-spacing":"0px",
                "-webkit-box-align":"stretch",
                "-webkit-box-direction":"normal",
                "-webkit-box-flex":"0",
                "-webkit-box-flex-group":"1",
                "-webkit-box-lines":"single",
                "-webkit-box-ordinal-group":"1",
                "-webkit-box-orient":"horizontal",
                "-webkit-box-pack":"start",
                "-webkit-box-reflect":"none",
                "-webkit-box-shadow":"none",
                "-webkit-color-correction":"default",
                "-webkit-column-break-after":"auto",
                "-webkit-column-break-before":"auto",
                "-webkit-column-break-inside":"auto",
                "-webkit-column-count":"auto",
                "-webkit-column-gap":"normal",
                "-webkit-column-rule-color":"rgb(255, 0, 0)",
                "-webkit-column-rule-style":"none",
                "-webkit-column-rule-width":"0px",
                "-webkit-column-span":"1",
                "-webkit-column-width":"auto",
                "-webkit-font-smoothing":"auto",
                "-webkit-highlight":"none",
                "-webkit-hyphenate-character":"auto",
                "-webkit-hyphenate-limit-after":"auto",
                "-webkit-hyphenate-limit-before":"auto",
                "-webkit-hyphens":"manual",
                "-webkit-line-box-contain":"block inline replaced",
                "-webkit-line-break":"normal",
                "-webkit-line-clamp":"none",
                "-webkit-locale":"auto",
                "-webkit-margin-after-collapse":"collapse",
                "-webkit-margin-before-collapse":"collapse",
                "-webkit-marquee-direction":"auto",
                "-webkit-marquee-increment":"6px",
                "-webkit-marquee-repetition":"infinite",
                "-webkit-marquee-style":"scroll",
                "-webkit-mask-attachment":"scroll",
                "-webkit-mask-box-image":"none",
                "-webkit-mask-clip":"border-box",
                "-webkit-mask-composite":"source-over",
                "-webkit-mask-image":"none",
                "-webkit-mask-origin":"border-box",
                "-webkit-mask-position":"0% 0%",
                "-webkit-mask-repeat":"repeat",
                "-webkit-mask-size":"auto auto",
                "-webkit-nbsp-mode":"normal",
                "-webkit-perspective":"none",
                "-webkit-perspective-origin":"0px 0px",
                "-webkit-rtl-ordering":"logical",
                "-webkit-svg-shadow":"none",
                "-webkit-text-combine":"none",
                "-webkit-text-decorations-in-effect":"none",
                "-webkit-text-emphasis-color":"rgb(255, 0, 0)",
                "-webkit-text-emphasis-position":"over",
                "-webkit-text-emphasis-style":"none",
                "-webkit-text-fill-color":"rgb(255, 0, 0)",
                "-webkit-text-orientation":"vertical-right",
                "-webkit-text-security":"none",
                "-webkit-text-stroke-color":"rgb(255, 0, 0)",
                "-webkit-text-stroke-width":"0px",
                "-webkit-transform":"none",
                "-webkit-transform-origin":"0px 0px",
                "-webkit-transform-style":"flat",
                "-webkit-transition-delay":"0s",
                "-webkit-transition-duration":"0s",
                "-webkit-transition-property":"all",
                "-webkit-transition-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
                "-webkit-user-drag":"auto",
                "-webkit-user-modify":"read-only",
                "-webkit-user-select":"text",
                "-webkit-writing-mode":"horizontal-tb",
                "alignment-baseline":"auto",
                "background-attachment":"scroll",
                "background-clip":"border-box",
                "background-color":"rgba(0, 0, 0, 0)",
                "background-image":"none",
                "background-origin":"padding-box",
                "background-position":"0% 0%",
                "background-repeat":"repeat",
                "background-size":"auto auto",
                "baseline-shift":"baseline",
                "border-bottom-color":"rgb(255, 0, 0)",
                "border-bottom-left-radius":"0px",
                "border-bottom-right-radius":"0px",
                "border-bottom-style":"none",
                "border-bottom-width":"0px",
                "border-collapse":"separate",
                "border-left-color":"rgb(255, 0, 0)",
                "border-left-style":"none",
                "border-left-width":"0px",
                "border-right-color":"rgb(255, 0, 0)",
                "border-right-style":"none",
                "border-right-width":"0px",
                "border-top-color":"rgb(255, 0, 0)",
                "border-top-left-radius":"0px",
                "border-top-right-radius":"0px",
                "border-top-style":"none",
                "border-top-width":"0px",
                "bottom":"auto",
                "box-shadow":"none",
                "box-sizing":"content-box",
                "caption-side":"top",
                "clear":"none",
                "clip":"auto",
                "clip-path":"none",
                "clip-rule":"nonzero",
                "color":"rgb(255, 0, 0)",
                "color-interpolation":"srgb",
                "color-interpolation-filters":"linearrgb",
                "color-rendering":"auto",
                "cursor":"auto",
                "direction":"ltr",
                "display":"inline",
                "dominant-baseline":"auto",
                "empty-cells":"show",
                "fill":"#000000",
                "fill-opacity":"1",
                "fill-rule":"nonzero",
                "filter":"none",
                "float":"none",
                "flood-color":"rgb(0, 0, 0)",
                "flood-opacity":"1",
                "font-family":"'Nimbus Sans L'",
                "font-size":"32px",
                "font-style":"italic",
                "font-variant":"normal",
                "font-weight":"bold",
                "glyph-orientation-horizontal":"0deg",
                "glyph-orientation-vertical":"auto",
                "height":"0px",
                "image-rendering":"auto",
                "kerning":"0",
                "left":"auto",
                "letter-spacing":"normal",
                "lighting-color":"rgb(255, 255, 255)",
                "line-height":"normal",
                "list-style-image":"none",
                "list-style-position":"outside",
                "list-style-type":"disc",
                "margin-bottom":"0px",
                "margin-left":"0px",
                "margin-right":"0px",
                "margin-top":"0px",
                "marker-end":"none",
                "marker-mid":"none",
                "marker-start":"none",
                "mask":"none",
                "max-height":"none",
                "max-width":"none",
                "min-height":"0px",
                "min-width":"0px",
                "opacity":"1",
                "orphans":"2",
                "outline-color":"rgb(255, 0, 0)",
                "outline-style":"none",
                "outline-width":"0px",
                "overflow-x":"visible",
                "overflow-y":"visible",
                "padding-bottom":"0px",
                "padding-left":"0px",
                "padding-right":"0px",
                "padding-top":"0px",
                "page-break-after":"auto",
                "page-break-before":"auto",
                "page-break-inside":"auto",
                "pointer-events":"auto",
                "position":"static",
                "resize":"none",
                "right":"auto",
                "shape-rendering":"auto",
                "speak":"normal",
                "stop-color":"rgb(0, 0, 0)",
                "stop-opacity":"1",
                "stroke":"none",
                "stroke-dasharray":"none",
                "stroke-dashoffset":"0",
                "stroke-linecap":"butt",
                "stroke-linejoin":"miter",
                "stroke-miterlimit":"4",
                "stroke-opacity":"1",
                "stroke-width":"1",
                "table-layout":"auto",
                "text-align":"-webkit-auto",
                "text-anchor":"start",
                "text-decoration":"none",
                "text-indent":"0px",
                "text-overflow":"clip",
                "text-rendering":"auto",
                "text-shadow":"none",
                "text-transform":"none",
                "top":"auto",
                "unicode-bidi":"normal",
                "vector-effect":"none",
                "vertical-align":"baseline",
                "visibility":"visible",
                "white-space":"normal",
                "widows":"2",
                "width":"0px",
                "word-break":"normal",
                "word-spacing":"0px",
                "word-wrap":"normal",
                "writing-mode":"lr-tb",
                "z-index":"auto",
                "zoom":"1"
              },
              "children":[

              ],
              "ignore":false,
              "rules":[

              ],
              "selector":"BODY>H1:nth-child(1)>EM:nth-child(1)"
            }
          ],
          "ignore":false,
          "rules":[
            {
              "attributes":{
                "color":"rgb(255, 0, 0)"
              },
              "selector":"h1",
              "sheet":"http://localhost:" + port + "/sample.css"
            }
          ],
          "selector":"BODY>H1:nth-child(1)"
        },
        {
          "attributes":{
            "-webkit-animation-delay":"0s",
            "-webkit-animation-direction":"normal",
            "-webkit-animation-duration":"0s",
            "-webkit-animation-fill-mode":"none",
            "-webkit-animation-iteration-count":"1",
            "-webkit-animation-name":"none",
            "-webkit-animation-play-state":"running",
            "-webkit-animation-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-appearance":"none",
            "-webkit-backface-visibility":"visible",
            "-webkit-background-clip":"border-box",
            "-webkit-background-composite":"source-over",
            "-webkit-background-origin":"padding-box",
            "-webkit-background-size":"auto auto",
            "-webkit-border-fit":"border",
            "-webkit-border-horizontal-spacing":"0px",
            "-webkit-border-image":"none",
            "-webkit-border-vertical-spacing":"0px",
            "-webkit-box-align":"stretch",
            "-webkit-box-direction":"normal",
            "-webkit-box-flex":"0",
            "-webkit-box-flex-group":"1",
            "-webkit-box-lines":"single",
            "-webkit-box-ordinal-group":"1",
            "-webkit-box-orient":"horizontal",
            "-webkit-box-pack":"start",
            "-webkit-box-reflect":"none",
            "-webkit-box-shadow":"none",
            "-webkit-color-correction":"default",
            "-webkit-column-break-after":"auto",
            "-webkit-column-break-before":"auto",
            "-webkit-column-break-inside":"auto",
            "-webkit-column-count":"auto",
            "-webkit-column-gap":"normal",
            "-webkit-column-rule-color":"rgb(0, 0, 0)",
            "-webkit-column-rule-style":"none",
            "-webkit-column-rule-width":"0px",
            "-webkit-column-span":"1",
            "-webkit-column-width":"auto",
            "-webkit-font-smoothing":"auto",
            "-webkit-highlight":"none",
            "-webkit-hyphenate-character":"auto",
            "-webkit-hyphenate-limit-after":"auto",
            "-webkit-hyphenate-limit-before":"auto",
            "-webkit-hyphens":"manual",
            "-webkit-line-box-contain":"block inline replaced",
            "-webkit-line-break":"normal",
            "-webkit-line-clamp":"none",
            "-webkit-locale":"auto",
            "-webkit-margin-after-collapse":"collapse",
            "-webkit-margin-before-collapse":"collapse",
            "-webkit-marquee-direction":"auto",
            "-webkit-marquee-increment":"6px",
            "-webkit-marquee-repetition":"infinite",
            "-webkit-marquee-style":"scroll",
            "-webkit-mask-attachment":"scroll",
            "-webkit-mask-box-image":"none",
            "-webkit-mask-clip":"border-box",
            "-webkit-mask-composite":"source-over",
            "-webkit-mask-image":"none",
            "-webkit-mask-origin":"border-box",
            "-webkit-mask-position":"0% 0%",
            "-webkit-mask-repeat":"repeat",
            "-webkit-mask-size":"auto auto",
            "-webkit-nbsp-mode":"normal",
            "-webkit-perspective":"none",
            "-webkit-perspective-origin":"360px 400px",
            "-webkit-rtl-ordering":"logical",
            "-webkit-svg-shadow":"none",
            "-webkit-text-combine":"none",
            "-webkit-text-decorations-in-effect":"none",
            "-webkit-text-emphasis-color":"rgb(0, 0, 0)",
            "-webkit-text-emphasis-position":"over",
            "-webkit-text-emphasis-style":"none",
            "-webkit-text-fill-color":"rgb(0, 0, 0)",
            "-webkit-text-orientation":"vertical-right",
            "-webkit-text-security":"none",
            "-webkit-text-stroke-color":"rgb(0, 0, 0)",
            "-webkit-text-stroke-width":"0px",
            "-webkit-transform":"none",
            "-webkit-transform-origin":"360px 400px",
            "-webkit-transform-style":"flat",
            "-webkit-transition-delay":"0s",
            "-webkit-transition-duration":"0s",
            "-webkit-transition-property":"all",
            "-webkit-transition-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-user-drag":"auto",
            "-webkit-user-modify":"read-only",
            "-webkit-user-select":"text",
            "-webkit-writing-mode":"horizontal-tb",
            "alignment-baseline":"auto",
            "background-attachment":"scroll",
            "background-clip":"border-box",
            "background-color":"rgba(0, 0, 0, 0)",
            "background-image":"none",
            "background-origin":"padding-box",
            "background-position":"0% 0%",
            "background-repeat":"repeat",
            "background-size":"auto auto",
            "baseline-shift":"baseline",
            "border-bottom-color":"rgb(0, 0, 0)",
            "border-bottom-left-radius":"0px",
            "border-bottom-right-radius":"0px",
            "border-bottom-style":"none",
            "border-bottom-width":"0px",
            "border-collapse":"separate",
            "border-left-color":"rgb(0, 0, 0)",
            "border-left-style":"none",
            "border-left-width":"0px",
            "border-right-color":"rgb(0, 0, 0)",
            "border-right-style":"none",
            "border-right-width":"0px",
            "border-top-color":"rgb(0, 0, 0)",
            "border-top-left-radius":"0px",
            "border-top-right-radius":"0px",
            "border-top-style":"none",
            "border-top-width":"0px",
            "bottom":"auto",
            "box-shadow":"none",
            "box-sizing":"content-box",
            "caption-side":"top",
            "clear":"none",
            "clip":"auto",
            "clip-path":"none",
            "clip-rule":"nonzero",
            "color":"rgb(0, 0, 0)",
            "color-interpolation":"srgb",
            "color-interpolation-filters":"linearrgb",
            "color-rendering":"auto",
            "cursor":"auto",
            "direction":"ltr",
            "display":"block",
            "dominant-baseline":"auto",
            "empty-cells":"show",
            "fill":"#000000",
            "fill-opacity":"1",
            "fill-rule":"nonzero",
            "filter":"none",
            "float":"none",
            "flood-color":"rgb(0, 0, 0)",
            "flood-opacity":"1",
            "font-family":"'Nimbus Sans L'",
            "font-size":"16px",
            "font-style":"normal",
            "font-variant":"normal",
            "font-weight":"normal",
            "glyph-orientation-horizontal":"0deg",
            "glyph-orientation-vertical":"auto",
            "height":"800px",
            "image-rendering":"auto",
            "kerning":"0",
            "left":"auto",
            "letter-spacing":"normal",
            "lighting-color":"rgb(255, 255, 255)",
            "line-height":"normal",
            "list-style-image":"none",
            "list-style-position":"outside",
            "list-style-type":"disc",
            "margin-bottom":"0px",
            "margin-left":"0px",
            "margin-right":"0px",
            "margin-top":"0px",
            "marker-end":"none",
            "marker-mid":"none",
            "marker-start":"none",
            "mask":"none",
            "max-height":"none",
            "max-width":"none",
            "min-height":"0px",
            "min-width":"0px",
            "opacity":"1",
            "orphans":"2",
            "outline-color":"rgb(0, 0, 0)",
            "outline-style":"none",
            "outline-width":"0px",
            "overflow-x":"visible",
            "overflow-y":"visible",
            "padding-bottom":"0px",
            "padding-left":"0px",
            "padding-right":"0px",
            "padding-top":"0px",
            "page-break-after":"auto",
            "page-break-before":"auto",
            "page-break-inside":"auto",
            "pointer-events":"auto",
            "position":"static",
            "resize":"none",
            "right":"auto",
            "shape-rendering":"auto",
            "speak":"normal",
            "stop-color":"rgb(0, 0, 0)",
            "stop-opacity":"1",
            "stroke":"none",
            "stroke-dasharray":"none",
            "stroke-dashoffset":"0",
            "stroke-linecap":"butt",
            "stroke-linejoin":"miter",
            "stroke-miterlimit":"4",
            "stroke-opacity":"1",
            "stroke-width":"1",
            "table-layout":"auto",
            "text-align":"-webkit-auto",
            "text-anchor":"start",
            "text-decoration":"none",
            "text-indent":"0px",
            "text-overflow":"clip",
            "text-rendering":"auto",
            "text-shadow":"none",
            "text-transform":"none",
            "top":"auto",
            "unicode-bidi":"normal",
            "vector-effect":"none",
            "vertical-align":"baseline",
            "visibility":"visible",
            "white-space":"normal",
            "widows":"2",
            "width":"720px",
            "word-break":"normal",
            "word-spacing":"0px",
            "word-wrap":"normal",
            "writing-mode":"lr-tb",
            "z-index":"0",
            "zoom":"1"
          },
          "children":[

          ],
          "ignore":true,
          "selector":"HTML"
        },
        {
          "attributes":{
            "-webkit-animation-delay":"0s",
            "-webkit-animation-direction":"normal",
            "-webkit-animation-duration":"0s",
            "-webkit-animation-fill-mode":"none",
            "-webkit-animation-iteration-count":"1",
            "-webkit-animation-name":"none",
            "-webkit-animation-play-state":"running",
            "-webkit-animation-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-appearance":"none",
            "-webkit-backface-visibility":"visible",
            "-webkit-background-clip":"border-box",
            "-webkit-background-composite":"source-over",
            "-webkit-background-origin":"padding-box",
            "-webkit-background-size":"auto auto",
            "-webkit-border-fit":"border",
            "-webkit-border-horizontal-spacing":"0px",
            "-webkit-border-image":"none",
            "-webkit-border-vertical-spacing":"0px",
            "-webkit-box-align":"stretch",
            "-webkit-box-direction":"normal",
            "-webkit-box-flex":"0",
            "-webkit-box-flex-group":"1",
            "-webkit-box-lines":"single",
            "-webkit-box-ordinal-group":"1",
            "-webkit-box-orient":"horizontal",
            "-webkit-box-pack":"start",
            "-webkit-box-reflect":"none",
            "-webkit-box-shadow":"none",
            "-webkit-color-correction":"default",
            "-webkit-column-break-after":"auto",
            "-webkit-column-break-before":"auto",
            "-webkit-column-break-inside":"auto",
            "-webkit-column-count":"auto",
            "-webkit-column-gap":"normal",
            "-webkit-column-rule-color":"rgb(0, 0, 0)",
            "-webkit-column-rule-style":"none",
            "-webkit-column-rule-width":"0px",
            "-webkit-column-span":"1",
            "-webkit-column-width":"auto",
            "-webkit-font-smoothing":"auto",
            "-webkit-highlight":"none",
            "-webkit-hyphenate-character":"auto",
            "-webkit-hyphenate-limit-after":"auto",
            "-webkit-hyphenate-limit-before":"auto",
            "-webkit-hyphens":"manual",
            "-webkit-line-box-contain":"block inline replaced",
            "-webkit-line-break":"normal",
            "-webkit-line-clamp":"none",
            "-webkit-locale":"auto",
            "-webkit-margin-after-collapse":"collapse",
            "-webkit-margin-before-collapse":"collapse",
            "-webkit-marquee-direction":"auto",
            "-webkit-marquee-increment":"6px",
            "-webkit-marquee-repetition":"infinite",
            "-webkit-marquee-style":"scroll",
            "-webkit-mask-attachment":"scroll",
            "-webkit-mask-box-image":"none",
            "-webkit-mask-clip":"border-box",
            "-webkit-mask-composite":"source-over",
            "-webkit-mask-image":"none",
            "-webkit-mask-origin":"border-box",
            "-webkit-mask-position":"0% 0%",
            "-webkit-mask-repeat":"repeat",
            "-webkit-mask-size":"auto auto",
            "-webkit-nbsp-mode":"normal",
            "-webkit-perspective":"none",
            "-webkit-perspective-origin":"352px 385px",
            "-webkit-rtl-ordering":"logical",
            "-webkit-svg-shadow":"none",
            "-webkit-text-combine":"none",
            "-webkit-text-decorations-in-effect":"none",
            "-webkit-text-emphasis-color":"rgb(0, 0, 0)",
            "-webkit-text-emphasis-position":"over",
            "-webkit-text-emphasis-style":"none",
            "-webkit-text-fill-color":"rgb(0, 0, 0)",
            "-webkit-text-orientation":"vertical-right",
            "-webkit-text-security":"none",
            "-webkit-text-stroke-color":"rgb(0, 0, 0)",
            "-webkit-text-stroke-width":"0px",
            "-webkit-transform":"none",
            "-webkit-transform-origin":"352px 385px",
            "-webkit-transform-style":"flat",
            "-webkit-transition-delay":"0s",
            "-webkit-transition-duration":"0s",
            "-webkit-transition-property":"all",
            "-webkit-transition-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-user-drag":"auto",
            "-webkit-user-modify":"read-only",
            "-webkit-user-select":"text",
            "-webkit-writing-mode":"horizontal-tb",
            "alignment-baseline":"auto",
            "background-attachment":"scroll",
            "background-clip":"border-box",
            "background-color":"rgba(0, 0, 0, 0)",
            "background-image":"none",
            "background-origin":"padding-box",
            "background-position":"0% 0%",
            "background-repeat":"repeat",
            "background-size":"auto auto",
            "baseline-shift":"baseline",
            "border-bottom-color":"rgb(0, 0, 0)",
            "border-bottom-left-radius":"0px",
            "border-bottom-right-radius":"0px",
            "border-bottom-style":"none",
            "border-bottom-width":"0px",
            "border-collapse":"separate",
            "border-left-color":"rgb(0, 0, 0)",
            "border-left-style":"none",
            "border-left-width":"0px",
            "border-right-color":"rgb(0, 0, 0)",
            "border-right-style":"none",
            "border-right-width":"0px",
            "border-top-color":"rgb(0, 0, 0)",
            "border-top-left-radius":"0px",
            "border-top-right-radius":"0px",
            "border-top-style":"none",
            "border-top-width":"0px",
            "bottom":"auto",
            "box-shadow":"none",
            "box-sizing":"content-box",
            "caption-side":"top",
            "clear":"none",
            "clip":"auto",
            "clip-path":"none",
            "clip-rule":"nonzero",
            "color":"rgb(0, 0, 0)",
            "color-interpolation":"srgb",
            "color-interpolation-filters":"linearrgb",
            "color-rendering":"auto",
            "cursor":"auto",
            "direction":"ltr",
            "display":"block",
            "dominant-baseline":"auto",
            "empty-cells":"show",
            "fill":"#000000",
            "fill-opacity":"1",
            "fill-rule":"nonzero",
            "filter":"none",
            "float":"none",
            "flood-color":"rgb(0, 0, 0)",
            "flood-opacity":"1",
            "font-family":"'Nimbus Sans L'",
            "font-size":"16px",
            "font-style":"normal",
            "font-variant":"normal",
            "font-weight":"normal",
            "glyph-orientation-horizontal":"0deg",
            "glyph-orientation-vertical":"auto",
            "height":"771px",
            "image-rendering":"auto",
            "kerning":"0",
            "left":"auto",
            "letter-spacing":"normal",
            "lighting-color":"rgb(255, 255, 255)",
            "line-height":"normal",
            "list-style-image":"none",
            "list-style-position":"outside",
            "list-style-type":"disc",
            "margin-bottom":"8px",
            "margin-left":"8px",
            "margin-right":"8px",
            "margin-top":"8px",
            "marker-end":"none",
            "marker-mid":"none",
            "marker-start":"none",
            "mask":"none",
            "max-height":"none",
            "max-width":"none",
            "min-height":"0px",
            "min-width":"0px",
            "opacity":"1",
            "orphans":"2",
            "outline-color":"rgb(0, 0, 0)",
            "outline-style":"none",
            "outline-width":"0px",
            "overflow-x":"visible",
            "overflow-y":"visible",
            "padding-bottom":"0px",
            "padding-left":"0px",
            "padding-right":"0px",
            "padding-top":"0px",
            "page-break-after":"auto",
            "page-break-before":"auto",
            "page-break-inside":"auto",
            "pointer-events":"auto",
            "position":"static",
            "resize":"none",
            "right":"auto",
            "shape-rendering":"auto",
            "speak":"normal",
            "stop-color":"rgb(0, 0, 0)",
            "stop-opacity":"1",
            "stroke":"none",
            "stroke-dasharray":"none",
            "stroke-dashoffset":"0",
            "stroke-linecap":"butt",
            "stroke-linejoin":"miter",
            "stroke-miterlimit":"4",
            "stroke-opacity":"1",
            "stroke-width":"1",
            "table-layout":"auto",
            "text-align":"-webkit-auto",
            "text-anchor":"start",
            "text-decoration":"none",
            "text-indent":"0px",
            "text-overflow":"clip",
            "text-rendering":"auto",
            "text-shadow":"none",
            "text-transform":"none",
            "top":"auto",
            "unicode-bidi":"normal",
            "vector-effect":"none",
            "vertical-align":"baseline",
            "visibility":"visible",
            "white-space":"normal",
            "widows":"2",
            "width":"704px",
            "word-break":"normal",
            "word-spacing":"0px",
            "word-wrap":"normal",
            "writing-mode":"lr-tb",
            "z-index":"auto",
            "zoom":"1"
          },
          "children":[

          ],
          "ignore":true,
          "selector":"BODY"
        }
      ],
      "1024":[
        {
          "attributes":{
            "-webkit-animation-delay":"0s",
            "-webkit-animation-direction":"normal",
            "-webkit-animation-duration":"0s",
            "-webkit-animation-fill-mode":"none",
            "-webkit-animation-iteration-count":"1",
            "-webkit-animation-name":"none",
            "-webkit-animation-play-state":"running",
            "-webkit-animation-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-appearance":"none",
            "-webkit-backface-visibility":"visible",
            "-webkit-background-clip":"border-box",
            "-webkit-background-composite":"source-over",
            "-webkit-background-origin":"padding-box",
            "-webkit-background-size":"auto auto",
            "-webkit-border-fit":"border",
            "-webkit-border-horizontal-spacing":"0px",
            "-webkit-border-image":"none",
            "-webkit-border-vertical-spacing":"0px",
            "-webkit-box-align":"stretch",
            "-webkit-box-direction":"normal",
            "-webkit-box-flex":"0",
            "-webkit-box-flex-group":"1",
            "-webkit-box-lines":"single",
            "-webkit-box-ordinal-group":"1",
            "-webkit-box-orient":"horizontal",
            "-webkit-box-pack":"start",
            "-webkit-box-reflect":"none",
            "-webkit-box-shadow":"none",
            "-webkit-color-correction":"default",
            "-webkit-column-break-after":"auto",
            "-webkit-column-break-before":"auto",
            "-webkit-column-break-inside":"auto",
            "-webkit-column-count":"auto",
            "-webkit-column-gap":"normal",
            "-webkit-column-rule-color":"rgb(255, 0, 0)",
            "-webkit-column-rule-style":"none",
            "-webkit-column-rule-width":"0px",
            "-webkit-column-span":"1",
            "-webkit-column-width":"auto",
            "-webkit-font-smoothing":"auto",
            "-webkit-highlight":"none",
            "-webkit-hyphenate-character":"auto",
            "-webkit-hyphenate-limit-after":"auto",
            "-webkit-hyphenate-limit-before":"auto",
            "-webkit-hyphens":"manual",
            "-webkit-line-box-contain":"block inline replaced",
            "-webkit-line-break":"normal",
            "-webkit-line-clamp":"none",
            "-webkit-locale":"auto",
            "-webkit-margin-after-collapse":"collapse",
            "-webkit-margin-before-collapse":"collapse",
            "-webkit-marquee-direction":"auto",
            "-webkit-marquee-increment":"6px",
            "-webkit-marquee-repetition":"infinite",
            "-webkit-marquee-style":"scroll",
            "-webkit-mask-attachment":"scroll",
            "-webkit-mask-box-image":"none",
            "-webkit-mask-clip":"border-box",
            "-webkit-mask-composite":"source-over",
            "-webkit-mask-image":"none",
            "-webkit-mask-origin":"border-box",
            "-webkit-mask-position":"0% 0%",
            "-webkit-mask-repeat":"repeat",
            "-webkit-mask-size":"auto auto",
            "-webkit-nbsp-mode":"normal",
            "-webkit-perspective":"none",
            "-webkit-perspective-origin":"504px 21px",
            "-webkit-rtl-ordering":"logical",
            "-webkit-svg-shadow":"none",
            "-webkit-text-combine":"none",
            "-webkit-text-decorations-in-effect":"none",
            "-webkit-text-emphasis-color":"rgb(255, 0, 0)",
            "-webkit-text-emphasis-position":"over",
            "-webkit-text-emphasis-style":"none",
            "-webkit-text-fill-color":"rgb(255, 0, 0)",
            "-webkit-text-orientation":"vertical-right",
            "-webkit-text-security":"none",
            "-webkit-text-stroke-color":"rgb(255, 0, 0)",
            "-webkit-text-stroke-width":"0px",
            "-webkit-transform":"none",
            "-webkit-transform-origin":"504px 21px",
            "-webkit-transform-style":"flat",
            "-webkit-transition-delay":"0s",
            "-webkit-transition-duration":"0s",
            "-webkit-transition-property":"all",
            "-webkit-transition-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-user-drag":"auto",
            "-webkit-user-modify":"read-only",
            "-webkit-user-select":"text",
            "-webkit-writing-mode":"horizontal-tb",
            "alignment-baseline":"auto",
            "background-attachment":"scroll",
            "background-clip":"border-box",
            "background-color":"rgba(0, 0, 0, 0)",
            "background-image":"none",
            "background-origin":"padding-box",
            "background-position":"0% 0%",
            "background-repeat":"repeat",
            "background-size":"auto auto",
            "baseline-shift":"baseline",
            "border-bottom-color":"rgb(255, 0, 0)",
            "border-bottom-left-radius":"0px",
            "border-bottom-right-radius":"0px",
            "border-bottom-style":"none",
            "border-bottom-width":"0px",
            "border-collapse":"separate",
            "border-left-color":"rgb(255, 0, 0)",
            "border-left-style":"none",
            "border-left-width":"0px",
            "border-right-color":"rgb(255, 0, 0)",
            "border-right-style":"none",
            "border-right-width":"0px",
            "border-top-color":"rgb(255, 0, 0)",
            "border-top-left-radius":"0px",
            "border-top-right-radius":"0px",
            "border-top-style":"none",
            "border-top-width":"0px",
            "bottom":"auto",
            "box-shadow":"none",
            "box-sizing":"content-box",
            "caption-side":"top",
            "clear":"none",
            "clip":"auto",
            "clip-path":"none",
            "clip-rule":"nonzero",
            "color":"rgb(255, 0, 0)",
            "color-interpolation":"srgb",
            "color-interpolation-filters":"linearrgb",
            "color-rendering":"auto",
            "cursor":"auto",
            "direction":"ltr",
            "display":"block",
            "dominant-baseline":"auto",
            "empty-cells":"show",
            "fill":"#000000",
            "fill-opacity":"1",
            "fill-rule":"nonzero",
            "filter":"none",
            "float":"none",
            "flood-color":"rgb(0, 0, 0)",
            "flood-opacity":"1",
            "font-family":"'Nimbus Sans L'",
            "font-size":"32px",
            "font-style":"normal",
            "font-variant":"normal",
            "font-weight":"bold",
            "glyph-orientation-horizontal":"0deg",
            "glyph-orientation-vertical":"auto",
            "height":"42px",
            "image-rendering":"auto",
            "kerning":"0",
            "left":"auto",
            "letter-spacing":"normal",
            "lighting-color":"rgb(255, 255, 255)",
            "line-height":"normal",
            "list-style-image":"none",
            "list-style-position":"outside",
            "list-style-type":"disc",
            "margin-bottom":"21px",
            "margin-left":"0px",
            "margin-right":"0px",
            "margin-top":"21px",
            "marker-end":"none",
            "marker-mid":"none",
            "marker-start":"none",
            "mask":"none",
            "max-height":"none",
            "max-width":"none",
            "min-height":"0px",
            "min-width":"0px",
            "opacity":"1",
            "orphans":"2",
            "outline-color":"rgb(255, 0, 0)",
            "outline-style":"none",
            "outline-width":"0px",
            "overflow-x":"visible",
            "overflow-y":"visible",
            "padding-bottom":"0px",
            "padding-left":"0px",
            "padding-right":"0px",
            "padding-top":"0px",
            "page-break-after":"auto",
            "page-break-before":"auto",
            "page-break-inside":"auto",
            "pointer-events":"auto",
            "position":"static",
            "resize":"none",
            "right":"auto",
            "shape-rendering":"auto",
            "speak":"normal",
            "stop-color":"rgb(0, 0, 0)",
            "stop-opacity":"1",
            "stroke":"none",
            "stroke-dasharray":"none",
            "stroke-dashoffset":"0",
            "stroke-linecap":"butt",
            "stroke-linejoin":"miter",
            "stroke-miterlimit":"4",
            "stroke-opacity":"1",
            "stroke-width":"1",
            "table-layout":"auto",
            "text-align":"-webkit-auto",
            "text-anchor":"start",
            "text-decoration":"none",
            "text-indent":"0px",
            "text-overflow":"clip",
            "text-rendering":"auto",
            "text-shadow":"none",
            "text-transform":"none",
            "top":"auto",
            "unicode-bidi":"normal",
            "vector-effect":"none",
            "vertical-align":"baseline",
            "visibility":"visible",
            "white-space":"normal",
            "widows":"2",
            "width":"1008px",
            "word-break":"normal",
            "word-spacing":"0px",
            "word-wrap":"normal",
            "writing-mode":"lr-tb",
            "z-index":"auto",
            "zoom":"1"
          },
          "children":[
            {
              "attributes":{
                "-webkit-animation-delay":"0s",
                "-webkit-animation-direction":"normal",
                "-webkit-animation-duration":"0s",
                "-webkit-animation-fill-mode":"none",
                "-webkit-animation-iteration-count":"1",
                "-webkit-animation-name":"none",
                "-webkit-animation-play-state":"running",
                "-webkit-animation-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
                "-webkit-appearance":"none",
                "-webkit-backface-visibility":"visible",
                "-webkit-background-clip":"border-box",
                "-webkit-background-composite":"source-over",
                "-webkit-background-origin":"padding-box",
                "-webkit-background-size":"auto auto",
                "-webkit-border-fit":"border",
                "-webkit-border-horizontal-spacing":"0px",
                "-webkit-border-image":"none",
                "-webkit-border-vertical-spacing":"0px",
                "-webkit-box-align":"stretch",
                "-webkit-box-direction":"normal",
                "-webkit-box-flex":"0",
                "-webkit-box-flex-group":"1",
                "-webkit-box-lines":"single",
                "-webkit-box-ordinal-group":"1",
                "-webkit-box-orient":"horizontal",
                "-webkit-box-pack":"start",
                "-webkit-box-reflect":"none",
                "-webkit-box-shadow":"none",
                "-webkit-color-correction":"default",
                "-webkit-column-break-after":"auto",
                "-webkit-column-break-before":"auto",
                "-webkit-column-break-inside":"auto",
                "-webkit-column-count":"auto",
                "-webkit-column-gap":"normal",
                "-webkit-column-rule-color":"rgb(255, 0, 0)",
                "-webkit-column-rule-style":"none",
                "-webkit-column-rule-width":"0px",
                "-webkit-column-span":"1",
                "-webkit-column-width":"auto",
                "-webkit-font-smoothing":"auto",
                "-webkit-highlight":"none",
                "-webkit-hyphenate-character":"auto",
                "-webkit-hyphenate-limit-after":"auto",
                "-webkit-hyphenate-limit-before":"auto",
                "-webkit-hyphens":"manual",
                "-webkit-line-box-contain":"block inline replaced",
                "-webkit-line-break":"normal",
                "-webkit-line-clamp":"none",
                "-webkit-locale":"auto",
                "-webkit-margin-after-collapse":"collapse",
                "-webkit-margin-before-collapse":"collapse",
                "-webkit-marquee-direction":"auto",
                "-webkit-marquee-increment":"6px",
                "-webkit-marquee-repetition":"infinite",
                "-webkit-marquee-style":"scroll",
                "-webkit-mask-attachment":"scroll",
                "-webkit-mask-box-image":"none",
                "-webkit-mask-clip":"border-box",
                "-webkit-mask-composite":"source-over",
                "-webkit-mask-image":"none",
                "-webkit-mask-origin":"border-box",
                "-webkit-mask-position":"0% 0%",
                "-webkit-mask-repeat":"repeat",
                "-webkit-mask-size":"auto auto",
                "-webkit-nbsp-mode":"normal",
                "-webkit-perspective":"none",
                "-webkit-perspective-origin":"0px 0px",
                "-webkit-rtl-ordering":"logical",
                "-webkit-svg-shadow":"none",
                "-webkit-text-combine":"none",
                "-webkit-text-decorations-in-effect":"none",
                "-webkit-text-emphasis-color":"rgb(255, 0, 0)",
                "-webkit-text-emphasis-position":"over",
                "-webkit-text-emphasis-style":"none",
                "-webkit-text-fill-color":"rgb(255, 0, 0)",
                "-webkit-text-orientation":"vertical-right",
                "-webkit-text-security":"none",
                "-webkit-text-stroke-color":"rgb(255, 0, 0)",
                "-webkit-text-stroke-width":"0px",
                "-webkit-transform":"none",
                "-webkit-transform-origin":"0px 0px",
                "-webkit-transform-style":"flat",
                "-webkit-transition-delay":"0s",
                "-webkit-transition-duration":"0s",
                "-webkit-transition-property":"all",
                "-webkit-transition-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
                "-webkit-user-drag":"auto",
                "-webkit-user-modify":"read-only",
                "-webkit-user-select":"text",
                "-webkit-writing-mode":"horizontal-tb",
                "alignment-baseline":"auto",
                "background-attachment":"scroll",
                "background-clip":"border-box",
                "background-color":"rgba(0, 0, 0, 0)",
                "background-image":"none",
                "background-origin":"padding-box",
                "background-position":"0% 0%",
                "background-repeat":"repeat",
                "background-size":"auto auto",
                "baseline-shift":"baseline",
                "border-bottom-color":"rgb(255, 0, 0)",
                "border-bottom-left-radius":"0px",
                "border-bottom-right-radius":"0px",
                "border-bottom-style":"none",
                "border-bottom-width":"0px",
                "border-collapse":"separate",
                "border-left-color":"rgb(255, 0, 0)",
                "border-left-style":"none",
                "border-left-width":"0px",
                "border-right-color":"rgb(255, 0, 0)",
                "border-right-style":"none",
                "border-right-width":"0px",
                "border-top-color":"rgb(255, 0, 0)",
                "border-top-left-radius":"0px",
                "border-top-right-radius":"0px",
                "border-top-style":"none",
                "border-top-width":"0px",
                "bottom":"auto",
                "box-shadow":"none",
                "box-sizing":"content-box",
                "caption-side":"top",
                "clear":"none",
                "clip":"auto",
                "clip-path":"none",
                "clip-rule":"nonzero",
                "color":"rgb(255, 0, 0)",
                "color-interpolation":"srgb",
                "color-interpolation-filters":"linearrgb",
                "color-rendering":"auto",
                "cursor":"auto",
                "direction":"ltr",
                "display":"inline",
                "dominant-baseline":"auto",
                "empty-cells":"show",
                "fill":"#000000",
                "fill-opacity":"1",
                "fill-rule":"nonzero",
                "filter":"none",
                "float":"none",
                "flood-color":"rgb(0, 0, 0)",
                "flood-opacity":"1",
                "font-family":"'Nimbus Sans L'",
                "font-size":"32px",
                "font-style":"italic",
                "font-variant":"normal",
                "font-weight":"bold",
                "glyph-orientation-horizontal":"0deg",
                "glyph-orientation-vertical":"auto",
                "height":"0px",
                "image-rendering":"auto",
                "kerning":"0",
                "left":"auto",
                "letter-spacing":"normal",
                "lighting-color":"rgb(255, 255, 255)",
                "line-height":"normal",
                "list-style-image":"none",
                "list-style-position":"outside",
                "list-style-type":"disc",
                "margin-bottom":"0px",
                "margin-left":"0px",
                "margin-right":"0px",
                "margin-top":"0px",
                "marker-end":"none",
                "marker-mid":"none",
                "marker-start":"none",
                "mask":"none",
                "max-height":"none",
                "max-width":"none",
                "min-height":"0px",
                "min-width":"0px",
                "opacity":"1",
                "orphans":"2",
                "outline-color":"rgb(255, 0, 0)",
                "outline-style":"none",
                "outline-width":"0px",
                "overflow-x":"visible",
                "overflow-y":"visible",
                "padding-bottom":"0px",
                "padding-left":"0px",
                "padding-right":"0px",
                "padding-top":"0px",
                "page-break-after":"auto",
                "page-break-before":"auto",
                "page-break-inside":"auto",
                "pointer-events":"auto",
                "position":"static",
                "resize":"none",
                "right":"auto",
                "shape-rendering":"auto",
                "speak":"normal",
                "stop-color":"rgb(0, 0, 0)",
                "stop-opacity":"1",
                "stroke":"none",
                "stroke-dasharray":"none",
                "stroke-dashoffset":"0",
                "stroke-linecap":"butt",
                "stroke-linejoin":"miter",
                "stroke-miterlimit":"4",
                "stroke-opacity":"1",
                "stroke-width":"1",
                "table-layout":"auto",
                "text-align":"-webkit-auto",
                "text-anchor":"start",
                "text-decoration":"none",
                "text-indent":"0px",
                "text-overflow":"clip",
                "text-rendering":"auto",
                "text-shadow":"none",
                "text-transform":"none",
                "top":"auto",
                "unicode-bidi":"normal",
                "vector-effect":"none",
                "vertical-align":"baseline",
                "visibility":"visible",
                "white-space":"normal",
                "widows":"2",
                "width":"0px",
                "word-break":"normal",
                "word-spacing":"0px",
                "word-wrap":"normal",
                "writing-mode":"lr-tb",
                "z-index":"auto",
                "zoom":"1"
              },
              "children":[

              ],
              "ignore":false,
              "rules":[

              ],
              "selector":"BODY>H1:nth-child(1)>EM:nth-child(1)"
            }
          ],
          "ignore":false,
          "rules":[
            {
              "attributes":{
                "color":"rgb(255, 0, 0)"
              },
              "selector":"h1",
              "sheet":"http://localhost:" + port + "/sample.css"
            }
          ],
          "selector":"BODY>H1:nth-child(1)"
        },
        {
          "attributes":{
            "-webkit-animation-delay":"0s",
            "-webkit-animation-direction":"normal",
            "-webkit-animation-duration":"0s",
            "-webkit-animation-fill-mode":"none",
            "-webkit-animation-iteration-count":"1",
            "-webkit-animation-name":"none",
            "-webkit-animation-play-state":"running",
            "-webkit-animation-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-appearance":"none",
            "-webkit-backface-visibility":"visible",
            "-webkit-background-clip":"border-box",
            "-webkit-background-composite":"source-over",
            "-webkit-background-origin":"padding-box",
            "-webkit-background-size":"auto auto",
            "-webkit-border-fit":"border",
            "-webkit-border-horizontal-spacing":"0px",
            "-webkit-border-image":"none",
            "-webkit-border-vertical-spacing":"0px",
            "-webkit-box-align":"stretch",
            "-webkit-box-direction":"normal",
            "-webkit-box-flex":"0",
            "-webkit-box-flex-group":"1",
            "-webkit-box-lines":"single",
            "-webkit-box-ordinal-group":"1",
            "-webkit-box-orient":"horizontal",
            "-webkit-box-pack":"start",
            "-webkit-box-reflect":"none",
            "-webkit-box-shadow":"none",
            "-webkit-color-correction":"default",
            "-webkit-column-break-after":"auto",
            "-webkit-column-break-before":"auto",
            "-webkit-column-break-inside":"auto",
            "-webkit-column-count":"auto",
            "-webkit-column-gap":"normal",
            "-webkit-column-rule-color":"rgb(0, 0, 0)",
            "-webkit-column-rule-style":"none",
            "-webkit-column-rule-width":"0px",
            "-webkit-column-span":"1",
            "-webkit-column-width":"auto",
            "-webkit-font-smoothing":"auto",
            "-webkit-highlight":"none",
            "-webkit-hyphenate-character":"auto",
            "-webkit-hyphenate-limit-after":"auto",
            "-webkit-hyphenate-limit-before":"auto",
            "-webkit-hyphens":"manual",
            "-webkit-line-box-contain":"block inline replaced",
            "-webkit-line-break":"normal",
            "-webkit-line-clamp":"none",
            "-webkit-locale":"auto",
            "-webkit-margin-after-collapse":"collapse",
            "-webkit-margin-before-collapse":"collapse",
            "-webkit-marquee-direction":"auto",
            "-webkit-marquee-increment":"6px",
            "-webkit-marquee-repetition":"infinite",
            "-webkit-marquee-style":"scroll",
            "-webkit-mask-attachment":"scroll",
            "-webkit-mask-box-image":"none",
            "-webkit-mask-clip":"border-box",
            "-webkit-mask-composite":"source-over",
            "-webkit-mask-image":"none",
            "-webkit-mask-origin":"border-box",
            "-webkit-mask-position":"0% 0%",
            "-webkit-mask-repeat":"repeat",
            "-webkit-mask-size":"auto auto",
            "-webkit-nbsp-mode":"normal",
            "-webkit-perspective":"none",
            "-webkit-perspective-origin":"512px 400px",
            "-webkit-rtl-ordering":"logical",
            "-webkit-svg-shadow":"none",
            "-webkit-text-combine":"none",
            "-webkit-text-decorations-in-effect":"none",
            "-webkit-text-emphasis-color":"rgb(0, 0, 0)",
            "-webkit-text-emphasis-position":"over",
            "-webkit-text-emphasis-style":"none",
            "-webkit-text-fill-color":"rgb(0, 0, 0)",
            "-webkit-text-orientation":"vertical-right",
            "-webkit-text-security":"none",
            "-webkit-text-stroke-color":"rgb(0, 0, 0)",
            "-webkit-text-stroke-width":"0px",
            "-webkit-transform":"none",
            "-webkit-transform-origin":"512px 400px",
            "-webkit-transform-style":"flat",
            "-webkit-transition-delay":"0s",
            "-webkit-transition-duration":"0s",
            "-webkit-transition-property":"all",
            "-webkit-transition-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-user-drag":"auto",
            "-webkit-user-modify":"read-only",
            "-webkit-user-select":"text",
            "-webkit-writing-mode":"horizontal-tb",
            "alignment-baseline":"auto",
            "background-attachment":"scroll",
            "background-clip":"border-box",
            "background-color":"rgba(0, 0, 0, 0)",
            "background-image":"none",
            "background-origin":"padding-box",
            "background-position":"0% 0%",
            "background-repeat":"repeat",
            "background-size":"auto auto",
            "baseline-shift":"baseline",
            "border-bottom-color":"rgb(0, 0, 0)",
            "border-bottom-left-radius":"0px",
            "border-bottom-right-radius":"0px",
            "border-bottom-style":"none",
            "border-bottom-width":"0px",
            "border-collapse":"separate",
            "border-left-color":"rgb(0, 0, 0)",
            "border-left-style":"none",
            "border-left-width":"0px",
            "border-right-color":"rgb(0, 0, 0)",
            "border-right-style":"none",
            "border-right-width":"0px",
            "border-top-color":"rgb(0, 0, 0)",
            "border-top-left-radius":"0px",
            "border-top-right-radius":"0px",
            "border-top-style":"none",
            "border-top-width":"0px",
            "bottom":"auto",
            "box-shadow":"none",
            "box-sizing":"content-box",
            "caption-side":"top",
            "clear":"none",
            "clip":"auto",
            "clip-path":"none",
            "clip-rule":"nonzero",
            "color":"rgb(0, 0, 0)",
            "color-interpolation":"srgb",
            "color-interpolation-filters":"linearrgb",
            "color-rendering":"auto",
            "cursor":"auto",
            "direction":"ltr",
            "display":"block",
            "dominant-baseline":"auto",
            "empty-cells":"show",
            "fill":"#000000",
            "fill-opacity":"1",
            "fill-rule":"nonzero",
            "filter":"none",
            "float":"none",
            "flood-color":"rgb(0, 0, 0)",
            "flood-opacity":"1",
            "font-family":"'Nimbus Sans L'",
            "font-size":"16px",
            "font-style":"normal",
            "font-variant":"normal",
            "font-weight":"normal",
            "glyph-orientation-horizontal":"0deg",
            "glyph-orientation-vertical":"auto",
            "height":"800px",
            "image-rendering":"auto",
            "kerning":"0",
            "left":"auto",
            "letter-spacing":"normal",
            "lighting-color":"rgb(255, 255, 255)",
            "line-height":"normal",
            "list-style-image":"none",
            "list-style-position":"outside",
            "list-style-type":"disc",
            "margin-bottom":"0px",
            "margin-left":"0px",
            "margin-right":"0px",
            "margin-top":"0px",
            "marker-end":"none",
            "marker-mid":"none",
            "marker-start":"none",
            "mask":"none",
            "max-height":"none",
            "max-width":"none",
            "min-height":"0px",
            "min-width":"0px",
            "opacity":"1",
            "orphans":"2",
            "outline-color":"rgb(0, 0, 0)",
            "outline-style":"none",
            "outline-width":"0px",
            "overflow-x":"visible",
            "overflow-y":"visible",
            "padding-bottom":"0px",
            "padding-left":"0px",
            "padding-right":"0px",
            "padding-top":"0px",
            "page-break-after":"auto",
            "page-break-before":"auto",
            "page-break-inside":"auto",
            "pointer-events":"auto",
            "position":"static",
            "resize":"none",
            "right":"auto",
            "shape-rendering":"auto",
            "speak":"normal",
            "stop-color":"rgb(0, 0, 0)",
            "stop-opacity":"1",
            "stroke":"none",
            "stroke-dasharray":"none",
            "stroke-dashoffset":"0",
            "stroke-linecap":"butt",
            "stroke-linejoin":"miter",
            "stroke-miterlimit":"4",
            "stroke-opacity":"1",
            "stroke-width":"1",
            "table-layout":"auto",
            "text-align":"-webkit-auto",
            "text-anchor":"start",
            "text-decoration":"none",
            "text-indent":"0px",
            "text-overflow":"clip",
            "text-rendering":"auto",
            "text-shadow":"none",
            "text-transform":"none",
            "top":"auto",
            "unicode-bidi":"normal",
            "vector-effect":"none",
            "vertical-align":"baseline",
            "visibility":"visible",
            "white-space":"normal",
            "widows":"2",
            "width":"1024px",
            "word-break":"normal",
            "word-spacing":"0px",
            "word-wrap":"normal",
            "writing-mode":"lr-tb",
            "z-index":"0",
            "zoom":"1"
          },
          "children":[

          ],
          "ignore":true,
          "selector":"HTML"
        },
        {
          "attributes":{
            "-webkit-animation-delay":"0s",
            "-webkit-animation-direction":"normal",
            "-webkit-animation-duration":"0s",
            "-webkit-animation-fill-mode":"none",
            "-webkit-animation-iteration-count":"1",
            "-webkit-animation-name":"none",
            "-webkit-animation-play-state":"running",
            "-webkit-animation-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-appearance":"none",
            "-webkit-backface-visibility":"visible",
            "-webkit-background-clip":"border-box",
            "-webkit-background-composite":"source-over",
            "-webkit-background-origin":"padding-box",
            "-webkit-background-size":"auto auto",
            "-webkit-border-fit":"border",
            "-webkit-border-horizontal-spacing":"0px",
            "-webkit-border-image":"none",
            "-webkit-border-vertical-spacing":"0px",
            "-webkit-box-align":"stretch",
            "-webkit-box-direction":"normal",
            "-webkit-box-flex":"0",
            "-webkit-box-flex-group":"1",
            "-webkit-box-lines":"single",
            "-webkit-box-ordinal-group":"1",
            "-webkit-box-orient":"horizontal",
            "-webkit-box-pack":"start",
            "-webkit-box-reflect":"none",
            "-webkit-box-shadow":"none",
            "-webkit-color-correction":"default",
            "-webkit-column-break-after":"auto",
            "-webkit-column-break-before":"auto",
            "-webkit-column-break-inside":"auto",
            "-webkit-column-count":"auto",
            "-webkit-column-gap":"normal",
            "-webkit-column-rule-color":"rgb(0, 0, 0)",
            "-webkit-column-rule-style":"none",
            "-webkit-column-rule-width":"0px",
            "-webkit-column-span":"1",
            "-webkit-column-width":"auto",
            "-webkit-font-smoothing":"auto",
            "-webkit-highlight":"none",
            "-webkit-hyphenate-character":"auto",
            "-webkit-hyphenate-limit-after":"auto",
            "-webkit-hyphenate-limit-before":"auto",
            "-webkit-hyphens":"manual",
            "-webkit-line-box-contain":"block inline replaced",
            "-webkit-line-break":"normal",
            "-webkit-line-clamp":"none",
            "-webkit-locale":"auto",
            "-webkit-margin-after-collapse":"collapse",
            "-webkit-margin-before-collapse":"collapse",
            "-webkit-marquee-direction":"auto",
            "-webkit-marquee-increment":"6px",
            "-webkit-marquee-repetition":"infinite",
            "-webkit-marquee-style":"scroll",
            "-webkit-mask-attachment":"scroll",
            "-webkit-mask-box-image":"none",
            "-webkit-mask-clip":"border-box",
            "-webkit-mask-composite":"source-over",
            "-webkit-mask-image":"none",
            "-webkit-mask-origin":"border-box",
            "-webkit-mask-position":"0% 0%",
            "-webkit-mask-repeat":"repeat",
            "-webkit-mask-size":"auto auto",
            "-webkit-nbsp-mode":"normal",
            "-webkit-perspective":"none",
            "-webkit-perspective-origin":"504px 385px",
            "-webkit-rtl-ordering":"logical",
            "-webkit-svg-shadow":"none",
            "-webkit-text-combine":"none",
            "-webkit-text-decorations-in-effect":"none",
            "-webkit-text-emphasis-color":"rgb(0, 0, 0)",
            "-webkit-text-emphasis-position":"over",
            "-webkit-text-emphasis-style":"none",
            "-webkit-text-fill-color":"rgb(0, 0, 0)",
            "-webkit-text-orientation":"vertical-right",
            "-webkit-text-security":"none",
            "-webkit-text-stroke-color":"rgb(0, 0, 0)",
            "-webkit-text-stroke-width":"0px",
            "-webkit-transform":"none",
            "-webkit-transform-origin":"504px 385px",
            "-webkit-transform-style":"flat",
            "-webkit-transition-delay":"0s",
            "-webkit-transition-duration":"0s",
            "-webkit-transition-property":"all",
            "-webkit-transition-timing-function":"cubic-bezier(0.25, 0.1, 0.25, 1)",
            "-webkit-user-drag":"auto",
            "-webkit-user-modify":"read-only",
            "-webkit-user-select":"text",
            "-webkit-writing-mode":"horizontal-tb",
            "alignment-baseline":"auto",
            "background-attachment":"scroll",
            "background-clip":"border-box",
            "background-color":"rgba(0, 0, 0, 0)",
            "background-image":"none",
            "background-origin":"padding-box",
            "background-position":"0% 0%",
            "background-repeat":"repeat",
            "background-size":"auto auto",
            "baseline-shift":"baseline",
            "border-bottom-color":"rgb(0, 0, 0)",
            "border-bottom-left-radius":"0px",
            "border-bottom-right-radius":"0px",
            "border-bottom-style":"none",
            "border-bottom-width":"0px",
            "border-collapse":"separate",
            "border-left-color":"rgb(0, 0, 0)",
            "border-left-style":"none",
            "border-left-width":"0px",
            "border-right-color":"rgb(0, 0, 0)",
            "border-right-style":"none",
            "border-right-width":"0px",
            "border-top-color":"rgb(0, 0, 0)",
            "border-top-left-radius":"0px",
            "border-top-right-radius":"0px",
            "border-top-style":"none",
            "border-top-width":"0px",
            "bottom":"auto",
            "box-shadow":"none",
            "box-sizing":"content-box",
            "caption-side":"top",
            "clear":"none",
            "clip":"auto",
            "clip-path":"none",
            "clip-rule":"nonzero",
            "color":"rgb(0, 0, 0)",
            "color-interpolation":"srgb",
            "color-interpolation-filters":"linearrgb",
            "color-rendering":"auto",
            "cursor":"auto",
            "direction":"ltr",
            "display":"block",
            "dominant-baseline":"auto",
            "empty-cells":"show",
            "fill":"#000000",
            "fill-opacity":"1",
            "fill-rule":"nonzero",
            "filter":"none",
            "float":"none",
            "flood-color":"rgb(0, 0, 0)",
            "flood-opacity":"1",
            "font-family":"'Nimbus Sans L'",
            "font-size":"16px",
            "font-style":"normal",
            "font-variant":"normal",
            "font-weight":"normal",
            "glyph-orientation-horizontal":"0deg",
            "glyph-orientation-vertical":"auto",
            "height":"771px",
            "image-rendering":"auto",
            "kerning":"0",
            "left":"auto",
            "letter-spacing":"normal",
            "lighting-color":"rgb(255, 255, 255)",
            "line-height":"normal",
            "list-style-image":"none",
            "list-style-position":"outside",
            "list-style-type":"disc",
            "margin-bottom":"8px",
            "margin-left":"8px",
            "margin-right":"8px",
            "margin-top":"8px",
            "marker-end":"none",
            "marker-mid":"none",
            "marker-start":"none",
            "mask":"none",
            "max-height":"none",
            "max-width":"none",
            "min-height":"0px",
            "min-width":"0px",
            "opacity":"1",
            "orphans":"2",
            "outline-color":"rgb(0, 0, 0)",
            "outline-style":"none",
            "outline-width":"0px",
            "overflow-x":"visible",
            "overflow-y":"visible",
            "padding-bottom":"0px",
            "padding-left":"0px",
            "padding-right":"0px",
            "padding-top":"0px",
            "page-break-after":"auto",
            "page-break-before":"auto",
            "page-break-inside":"auto",
            "pointer-events":"auto",
            "position":"static",
            "resize":"none",
            "right":"auto",
            "shape-rendering":"auto",
            "speak":"normal",
            "stop-color":"rgb(0, 0, 0)",
            "stop-opacity":"1",
            "stroke":"none",
            "stroke-dasharray":"none",
            "stroke-dashoffset":"0",
            "stroke-linecap":"butt",
            "stroke-linejoin":"miter",
            "stroke-miterlimit":"4",
            "stroke-opacity":"1",
            "stroke-width":"1",
            "table-layout":"auto",
            "text-align":"-webkit-auto",
            "text-anchor":"start",
            "text-decoration":"none",
            "text-indent":"0px",
            "text-overflow":"clip",
            "text-rendering":"auto",
            "text-shadow":"none",
            "text-transform":"none",
            "top":"auto",
            "unicode-bidi":"normal",
            "vector-effect":"none",
            "vertical-align":"baseline",
            "visibility":"visible",
            "white-space":"normal",
            "widows":"2",
            "width":"1008px",
            "word-break":"normal",
            "word-spacing":"0px",
            "word-wrap":"normal",
            "writing-mode":"lr-tb",
            "z-index":"auto",
            "zoom":"1"
          },
          "children":[

          ],
          "ignore":true,
          "selector":"BODY"
        }
      ]
    }
  }
];
